version: '3.6'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "$NGINX_PORT:80"
        depends_on:
            - php-fpm
            - mysql
        volumes:
            - "$PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "$PWD/flarum:/var/www/html"
        restart: always
        container_name: "flarum-nginx"
        networks:
            - flarum-net
    php-fpm:
        build:
            context: ./
            dockerfile: php-fpm/Dockerfile
        image: php:flarum
        expose:
            - "9000"
        volumes:
            - "$PWD/flarum:/var/www/html"
        restart: always
        container_name: "flarum-php-fpm"
        networks:
            - flarum-net
    composer:
        build: ./composer
        image: composer:mirror
        depends_on:
            - "php-fpm"
        volumes:
            - "$PWD/flarum:/var/www/html"
        command: "composer require csineneo/lang-simplified-chinese flagrow/upload:*"
        restart: on-failure
        container_name: "flarum-composer"
        networks:
            - flarum-net
    mysql:
        build: ./mysql
        image: mysql:flarum
        expose:
            - "3306"
        ports:
            - "127.0.0.1:$MYSQL_PORT:3306"
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
            - "$PWD/mysql/data:/var/lib/mysql"
            - "$PWD/mysql/dump:/opt/dump"
        restart: always
        container_name: "flarum-mysql"
        networks:
            - flarum-net
networks:
    flarum-net:
